/**
 * CHARACTERIZATION SCENARIOS CATALOG
 *
 * Defines 16 deterministic scenarios covering all domain-significant JumpMath behaviors.
 */

import { CharacterizationScenario } from './scenarioModel';

export const CHARACTERIZATION_SCENARIOS: CharacterizationScenario[] = [
  {
    id: 'APP_SESSION_LIFECYCLE',
    name: 'App Session Lifecycle & Level Clear',
    category: 'APP_SESSION',
    description: 'Verifies level start, sequential correct jumps across all 4 rows, and level completion win state.',
    levelId: 'f1_sum10',
    seed: 42,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'initial_ready' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'row1_landed' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 2 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'row2_landed' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 3 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'row3_landed' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 4 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'level_won' },
    ],
  },
  {
    id: 'MATH_SUM_TO',
    name: 'SumTo Mode Challenge Generation & Resolution',
    category: 'MATH',
    description: 'Verifies SumToMode target matching, decoy generation, and correct arithmetic resolution.',
    levelId: 'f1_sum10',
    seed: 101,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'sum_init' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'sum_row1_resolved' },
    ],
  },
  {
    id: 'MATH_DIFFERENCE',
    name: 'Difference Mode Generation & Resolution',
    category: 'MATH',
    description: 'Verifies DifferenceMode challenge generation and distractor uniqueness.',
    levelId: 'd4_diff15',
    seed: 202,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'diff_init' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'diff_row1_resolved' },
    ],
  },
  {
    id: 'MATH_MULTIPLY',
    name: 'Multiply Mode Generation & Resolution',
    category: 'MATH',
    description: 'Verifies MultiplyMode factor generation, option uniqueness, and correct resolution.',
    levelId: 'd3_mult2',
    seed: 303,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'mult_init' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'mult_row1_resolved' },
    ],
  },
  {
    id: 'MATH_SKIP_COUNT',
    name: 'Skip Count Mode Sequence Alignment',
    category: 'MATH',
    description: 'Verifies SkipCountMode step increments and alignment across platform rows.',
    levelId: 'd2_skip5',
    seed: 404,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'skip_init' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'skip_row1_resolved' },
    ],
  },
  {
    id: 'PLATFORM_HIT_CANONICAL',
    name: 'Platform Visual Body Hit Containment',
    category: 'PLATFORM',
    description: 'Verifies that pointer selection at the extreme edges of platform visual bodies successfully selects the platform.',
    levelId: 'f1_sum10',
    seed: 505,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'hit_test_ready' },
      // Select platform using exact coordinates calculated to fall on the outer visual body edge
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 10 },
      { type: 'CAPTURE_OBSERVATION', label: 'hit_test_in_flight' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 20 },
      { type: 'CAPTURE_OBSERVATION', label: 'hit_test_landed' },
    ],
  },
  {
    id: 'PLATFORM_WRONG_SELECTION',
    name: 'Platform Wrong Answer Shatter & Rebound',
    category: 'PLATFORM',
    description: 'Verifies platform shatter effect and player elastic bounce back to support row on wrong selection.',
    levelId: 'f1_sum10',
    seed: 606,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'before_wrong_selection' },
      { type: 'SELECT_WRONG_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 10 },
      { type: 'CAPTURE_OBSERVATION', label: 'wrong_bounce_midair' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'wrong_bounce_restored' },
    ],
  },
  {
    id: 'PLATFORM_DIAGONAL_ROUTE',
    name: 'Diagonal Progression Route & Actionable Framing',
    category: 'PLATFORM',
    description: 'Verifies diagonal camera follow and actionable-row framing on diagonal level d1_sum20.',
    levelId: 'd1_sum20',
    seed: 707,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'diagonal_init' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'diagonal_row1_landed' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 2 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'diagonal_row2_landed' },
    ],
  },
  {
    id: 'PLAYER_JUMP_FLIGHT',
    name: 'Player Jump Kinematics & Landing Squash',
    category: 'PLAYER',
    description: 'Verifies parabolic jump curve t in [0, 1] and squash/stretch recovery.',
    levelId: 'f1_sum10',
    seed: 808,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'jump_ready' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 5 },
      { type: 'CAPTURE_OBSERVATION', label: 'jump_t_early' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 8 },
      { type: 'CAPTURE_OBSERVATION', label: 'jump_t_apex' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 12 },
      { type: 'CAPTURE_OBSERVATION', label: 'jump_landed' },
    ],
  },
  {
    id: 'PLASMA_PURSUIT_ADVANCE',
    name: 'Plasma Constant Pursuit Advancement',
    category: 'PLASMA',
    description: 'Verifies constant configured pursuit speed advancement over 3 seconds.',
    levelId: 'f1_sum10',
    seed: 909,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'wave_t0' },
      { type: 'ADVANCE_TIME', dt: 1.0, steps: 1 },
      { type: 'CAPTURE_OBSERVATION', label: 'wave_t1' },
      { type: 'ADVANCE_TIME', dt: 1.0, steps: 1 },
      { type: 'CAPTURE_OBSERVATION', label: 'wave_t2' },
      { type: 'ADVANCE_TIME', dt: 1.0, steps: 1 },
      { type: 'CAPTURE_OBSERVATION', label: 'wave_t3' },
    ],
  },
  {
    id: 'PLASMA_COLLISION_RECOVERY',
    name: 'Plasma Collision, Death Transition & 350px Recovery',
    category: 'PLASMA',
    description: 'Verifies death triggered when wave reaches player, respawn with 350px recovery gap and shield.',
    levelId: 'f1_sum10',
    seed: 1010,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'pre_collision' },
      // Advance time until wave overtakes row 0 player
      { type: 'ADVANCE_TIME', dt: 0.1, steps: 120 },
      { type: 'CAPTURE_OBSERVATION', label: 'post_recovery' },
    ],
  },
  {
    id: 'TIMER_EXPIRATION',
    name: 'Timer Countdown & Expiration Death',
    category: 'TIMER',
    description: 'Verifies active timer countdown to 0, timeout death, and state reset.',
    levelId: 'f1_sum10',
    seed: 1111,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'timer_full' },
      { type: 'ADVANCE_TIME', dt: 1.0, steps: 5 },
      { type: 'CAPTURE_OBSERVATION', label: 'timer_half' },
      { type: 'ADVANCE_TIME', dt: 1.0, steps: 6 },
      { type: 'CAPTURE_OBSERVATION', label: 'timer_expired_death' },
    ],
  },
  {
    id: 'CAMPAIGN_SECTOR_PROGRESSION',
    name: 'Campaign Sector Lock Invariant',
    category: 'CAMPAIGN',
    description: 'Verifies sector unlock rules (Sector 1 open, Sector 2 locked until 1 cleared).',
    levelId: 'f1_sum10',
    seed: 1212,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'campaign_s1_open' },
    ],
  },
  {
    id: 'REVIEW_MODE_OVERRIDE',
    name: 'Review Mode Unlock Override & Progression Isolation',
    category: 'REVIEW',
    description: 'Verifies that review mode + unlock override allows selecting all 30 levels without mutating progress.',
    levelId: 'q4_mult7',
    seed: 1313,
    viewport: { width: 500, height: 800, dpr: 1 },
    initialSettings: { reviewMode: true, reviewUnlockAllLevels: true },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'review_direct_launch' },
    ],
  },
  {
    id: 'SETTINGS_STATE_CYCLE',
    name: 'Settings Staging & Cancel Cycle',
    category: 'SETTINGS',
    description: 'Verifies modal isolation and non-destructive configuration staging.',
    levelId: 'f1_sum10',
    seed: 1414,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'settings_normal' },
    ],
  },
  {
    id: 'MOBILE_VIEWPORT_DPR',
    name: 'Mobile Viewport Letterbox & Coordinate Unprojection',
    category: 'MOBILE',
    description: 'Verifies correct platform selection on simulated iPhone 15 Pro viewport (393x852, DPR 3).',
    levelId: 'f1_sum10',
    seed: 1515,
    viewport: { width: 393, height: 852, dpr: 3 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'mobile_init' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'mobile_row1_landed' },
    ],
  },
  {
    id: 'INPUT_SPAM_REJECTION',
    name: 'Rapid Input Spam While Jumping Rejection',
    category: 'PLAYER',
    description: 'Verifies that input taps received while zyx is in flight (jumping === true) are rejected.',
    levelId: 'f1_sum10',
    seed: 1616,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'pre_jump' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 5 },
      // Tap again while mid-air
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 2 },
      { type: 'CAPTURE_OBSERVATION', label: 'mid_jump_spam_blocked' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 25 },
      { type: 'CAPTURE_OBSERVATION', label: 'row1_landed_normally' },
    ],
  },
  {
    id: 'OUT_OF_ORDER_JUMP_REJECTION',
    name: 'Out-Of-Order Row Jump Selection Rejection',
    category: 'PLATFORM',
    description: 'Verifies that attempting to click row N+2 while at row N is ignored by candidate selection.',
    levelId: 'f1_sum10',
    seed: 1717,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'row0_start' },
      // Attempt click on row 2
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 2 },
      { type: 'CAPTURE_OBSERVATION', label: 'row2_attempt_ignored' },
      // Now valid click on row 1
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'row1_valid_landed' },
    ],
  },
  {
    id: 'MIDAIR_PLASMA_CATASTROPHE',
    name: 'Mid-Air Plasma Catastrophe & State Restoration',
    category: 'PLASMA',
    description: 'Verifies that death triggered mid-air restores travelPreview, safePose, and respawns cleanly.',
    levelId: 'f1_sum10',
    seed: 1818,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'pre_jump' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 10 },
      { type: 'CAPTURE_OBSERVATION', label: 'in_flight_preview_active' },
      { type: 'TRIGGER_DEATH', cause: 'wave' },
      { type: 'CAPTURE_OBSERVATION', label: 'midair_death_triggered' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 80 },
      { type: 'CAPTURE_OBSERVATION', label: 'respawned_safe_pose' },
    ],
  },
  {
    id: 'SHIELD_EXPIRATION_LIFECYCLE',
    name: 'Plasma Shield Lifecycle & Expiration',
    category: 'PLASMA',
    description: 'Verifies post-respawn shield duration and vulnerability restoration after shield expires.',
    levelId: 'f1_sum10',
    seed: 1919,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'TRIGGER_DEATH', cause: 'wave' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 80 },
      { type: 'CAPTURE_OBSERVATION', label: 'shield_active_post_respawn' },
      // Advance time beyond shield duration (1.25s)
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 90 },
      { type: 'CAPTURE_OBSERVATION', label: 'shield_expired_vulnerable' },
    ],
  },
  {
    id: 'SUBPIXEL_EDGE_HIT_CONTAINMENT',
    name: 'Sub-Pixel Platform Boundary Hit Containment',
    category: 'PLATFORM',
    description: 'Verifies that clicks near the mathematical outer rim of visual platform body register hits.',
    levelId: 'f1_sum10',
    seed: 2020,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'subpixel_ready' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'subpixel_landed' },
    ],
  },
  {
    id: 'LEVEL_CLEAR_HOLD_TRANSITION',
    name: 'Level Clear Victory Hold & Transition',
    category: 'APP_SESSION',
    description: 'Verifies that reaching row 4 sets completionPosted and holds simulation cleanly.',
    levelId: 'f1_sum10',
    seed: 2121,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 2 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 3 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 4 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'level_clear_hold' },
    ],
  },
  {
    id: 'VIEWPORT_RESIZE_STRESS',
    name: 'Dynamic Viewport Resize & Unprojection Stress',
    category: 'MOBILE',
    description: 'Verifies coordinate unprojection after resizing canvas viewport during active round.',
    levelId: 'f1_sum10',
    seed: 2222,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'before_resize' },
      { type: 'RESIZE_VIEWPORT', width: 393, height: 852 },
      { type: 'CAPTURE_OBSERVATION', label: 'after_resize' },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'post_resize_jump_landed' },
    ],
  },
  {
    id: 'HINT_ANGLE_TRACKING',
    name: 'Low-Timer Hint Angle Guidance',
    category: 'PLAYER',
    description: 'Verifies that zyx.targetAngle activates towards correct answer when timeLeft falls below threshold.',
    levelId: 'f1_sum10',
    seed: 2323,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'timer_high_no_hint' },
      // Advance time until timeLeft drops to hint ratio (pct <= 0.40)
      { type: 'ADVANCE_TIME', dt: 1.0, steps: 7 },
      { type: 'CAPTURE_OBSERVATION', label: 'timer_low_hint_active' },
    ],
  },
  {
    id: 'FLOW_STATE_COMBO_LIFECYCLE',
    name: 'Flow State Combo Activation & Decay',
    category: 'PLAYER',
    description: 'Verifies flow state activation upon combo threshold and deactivation upon low timer.',
    levelId: 'f1_sum10',
    seed: 2424,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 1 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 2 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'SELECT_CORRECT_ANSWER', rowIdx: 3 },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 30 },
      { type: 'CAPTURE_OBSERVATION', label: 'combo_accumulated' },
    ],
  },
  {
    id: 'HITSTOP_FRAME_COUNT_FREEZE',
    name: 'Hitstop Frame-Count Integration Freeze',
    category: 'PLASMA',
    description: 'Verifies that fireImpact triggers integer frame freeze during collision impact.',
    levelId: 'f1_sum10',
    seed: 2525,
    viewport: { width: 500, height: 800, dpr: 1 },
    steps: [
      { type: 'CAPTURE_OBSERVATION', label: 'pre_hitstop' },
      { type: 'TRIGGER_DEATH', cause: 'wave' },
      { type: 'CAPTURE_OBSERVATION', label: 'hitstop_frame_0' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 2 },
      { type: 'CAPTURE_OBSERVATION', label: 'hitstop_in_progress' },
      { type: 'ADVANCE_TIME', dt: 1 / 60, steps: 4 },
      { type: 'CAPTURE_OBSERVATION', label: 'hitstop_cleared' },
    ],
  },
];
